dentexchange/apps/employee/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url

from libs.decorators import login_required_for, EMPLOYEE, EMPLOYER
from membership.decorators import enforce_membership
from . import views

urlpatterns = patterns('',
    url(r'^$',
        login_required_for(EMPLOYEE)(
        enforce_membership(views.DashboardView.as_view())),
        name='dashboard'),
    url(r'^questionnaire/$',
        login_required_for(EMPLOYEE)(
        views.AddEmployeeQuestionnaireFromSignUpFormView.as_view()),
        name='questionnaire_signup_add'),
    url(r'^questionnaire/edit/(?P<pk>\d+)/$',
        login_required_for(EMPLOYEE)(enforce_membership(
        views.EditEmployeeQuestionnaireFromProfileFormView.as_view())),
        name='questionnaire_edit'),
    url(r'^questionnaire/add/$',
        login_required_for(EMPLOYEE)(enforce_membership(
        views.AddEmployeeQuestionnaireFromProfileFormView.as_view())),
        name='questionnaire_add'),
    url(r'^questionnaire/view/$',
        login_required_for((EMPLOYER, EMPLOYEE))(enforce_membership(
            views.PublicQuestionnaireDetailFromListView.as_view())),
        name='view_public_questionnaire_from_list'),
)

dentexchange/apps/employee/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic

from validatedfile.fields import ValidatedFileField

from libs import constants as lib_constants
from libs.models.indexable import IndexableModel
from matches.models import Match
from . import strings, constants


class EmployeeQuestionnaire(IndexableModel):
    user = models.OneToOneField(User,
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_USER)
    ### Job Position you're looking for
    job_position = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_JOB_POSITION,
        choices=constants.JOB_POSITION_CHOICES,
        blank=True, null=True)
    ### Type of Practice
    solo_practitioner = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SOLO_PRACTITIONER)
    multi_practitioner = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_MULTI_PRACTITIONER)
    corporate = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_CORPORATE)
    ### Patients' Method of Payment
    fee_for_service = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_FEE_FOR_SERVICE)
    insurance = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_INSURANCE)
    capitation_medicaid = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_CAPITATION_MEDICAID)
    ### Location
    zip_code = models.DecimalField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_ZIP_CODE,
        max_digits=5, decimal_places=0,
        blank=True, null=True)
    city = models.CharField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_CITY,
        max_length=100, blank=True)
    state = models.CharField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_STATE,
        choices=lib_constants.STATE_CHOICES,
        max_length=2, blank=True)
    distance = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_DISTANCE,
        choices=constants.DISTANCE_CHOICES,
        blank=True, null=True)
    ### Type of schedule required
    schedule_type = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SCHEDULE_TYPE,
        choices=constants.SCHEDULE_TYPE_CHOICES,
        default=constants.SCHEDULE_TYPE_CHOICES.PART_TIME)
    monday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_MONDAY_DAYTIME,
        default=False)
    monday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_MONDAY_EVENING,
        default=False)
    tuesday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_TUESDAY_DAYTIME,
        default=False)
    tuesday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_TUESDAY_EVENING,
        default=False)
    wednesday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_WEDNESDAY_DAYTIME,
        default=False)
    wednesday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_WEDNESDAY_EVENING,
        default=False)
    thursday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_THURSDAY_DAYTIME,
        default=False)
    thursday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_THURSDAY_EVENING,
        default=False)
    friday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_FRIDAY_DAYTIME,
        default=False)
    friday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_FRIDAY_EVENING,
        default=False)
    saturday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SATURDAY_DAYTIME,
        default=False)
    saturday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SATURDAY_EVENING,
        default=False)
    sunday_daytime = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SUNDAY_DAYTIME,
        default=False)
    sunday_evening = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SUNDAY_EVENING,
        default=False)
    ### Compensation
    compensation_type = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_COMPENSATION_TYPE,
        choices=constants.COMPENSATION_TYPE_CHOICES,
        default=constants.COMPENSATION_TYPE_CHOICES.HOURLY)
    hourly_wage = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_HOURLY_WAGE,
        choices=constants.HOURLY_WAGE_CHOICES,
        blank=True, null=True)
    annualy_wage = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_ANNUALY_WAGE,
        choices=constants.ANNUALY_WAGE_CHOICES,
        blank=True, null=True)
    production = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_PRODUCTION,
        default=False)
    collection = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_COLLECTION,
        default=False)
    ### Experience
    experience_years = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_EXPERIENCE_YEARS,
        choices=constants.EXPERIENCE_YEARS_CHOICES,
        blank=True, null=True)
    ### Education
    dental_school = models.CharField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_DENTAL_SCHOOL,
        max_length=200, blank=True)
    graduation_year = models.PositiveSmallIntegerField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_GRADUATION_YEAR,
        choices=constants.GRADUATION_YEAR_CHOICES,
        blank=True, null=True)
    ### Visa
    visa = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_VISA,
        choices=lib_constants.YES_NO_CHOICES,
        default=lib_constants.YES_NO_CHOICES.YES)
    ### Specific strengths
    specific_strengths = models.TextField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_SPECIFIC_STRENGTHS,
        blank=True)
    ### Visibility
    is_private = models.BooleanField(
        verbose_name=strings.EMPLOYEE_QUESTIONNAIRE_IS_PRIVATE,
        help_text=strings.EMPLOYEE_QUESTIONNAIRE_IS_PRIVATE_HELP_TEXT,
        default=False)
    matches = generic.GenericRelation(Match,
        content_type_field='match_content_type',
        object_id_field='match_object_id')

    class Meta(object):
        verbose_name = strings.EMPLOYEE_QUESTIONNAIRE_VERBOSE_NAME
        verbose_name_plural = strings.EMPLOYEE_QUESTIONNAIRE_VERBOSE_NAME_PLURAL

    def __unicode__(self):
        return self.user.email

    def get_email(self):
        return unicode(self)

    def get_location(self):
        return 


class Resume(models.Model):
    user = models.OneToOneField(User, verbose_name=strings.RESUME_USER)
    cv_file = ValidatedFileField(upload_to='employee/resumes',
        verbose_name=strings.RESUME_CV_FILE,
        help_text=strings.RESUME_CV_FILE_HELP_TEXT,
        max_upload_size=constants.RESUME_CV_FILE_MAX_UPLOAD_SIZE,
        content_types=constants.RESUME_CV_FILE_CONTENT_TYPES,
        null=True, blank=True)

    class Meta(object):
        verbose_name = strings.RESUME_VERBOSE_NAME
        verbose_name_plural = strings.RESUME_VERBOSE_NAME_PLURAL

    def __unicode__(self):
        return self.user.email

    def get_email(self):
        return unicode(self)

dentexchange/apps/employee/templates/employee/add_edit_employee_questionnaire_form.html
{% extends 'employee/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'employee/js/questionnaire.js' %}"></script>
<script type="text/javascript" src="{% static 'employee/js/add_edit_questionnaire.js' %}"></script>
{{ form.resume_form.media }}
{% endblock %}
{% block profile_content %}
<form method="post" action="." role="form">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-3">
            <h1 class="title">{% trans 'Profile' %}</h1>
        </div>
    </div>
    {% csrf_token %}
    {% include 'employee/employee_questionnaire_form.html' %}
    <div class="row">
        <div class="col-sm-4 col-sm-offset-5">
            {% buttons %}
            <div class="pull-right">
                <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            </div>
            {% endbuttons %}
        </div>
    </div>
</form>
{% endblock %}

dentexchange/apps/employee/templates/employee/add_employee_questionnaire_form.html
{% extends 'base/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
{% block scripts %}
<script type="text/javascript" src="{% static 'employee/js/questionnaire.js' %}"></script>
{{ form.resume_form.media }}
{% endblock %}
{% block content %}
<form method="post" action="{% url 'employee:questionnaire_signup_add' %}" role="form">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <h1>{% trans "Welcome to Dentexchange! Let's get started." %}</h1>
        </div>
    </div>
    {% include 'employee/employee_questionnaire_form.html' %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            {% buttons %}
            <div class="pull-right">
            {% if skippable %}
            <button type="submit" class="btn btn-primary">{% trans 'Continue editing' %}</button>
            <button type="submit" class="btn btn-info" name="_skip">{% trans 'Skip step for now' %} &gt;</button>
            {% else %}
            <button type="submit" class="btn btn-primary">{% trans 'Continue' %} &gt;</button>
            {% endif %}
            </div>
            {% endbuttons %}
        </div>
    </div>
</form>
{% endblock %}

dentexchange/apps/employee/templates/employee/base.html
{% extends 'base/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
{% block extrahead %}
<link href="{% static 'employee/css/base.css' %}" rel="stylesheet" type="text/css" />
{% block profile_extrahead %}{% endblock %}
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{% static 'base/js/profile_menu.js' %}"></script>
{% block profile_scripts %}{% endblock %}
{% endblock %}
{% block dashboard_menu %}
<li id="id_employee_profile_dashboard_menu"><a href="{% url 'employee:dashboard' %}">{% trans 'Dashboard' %}</a></li>
<li id="id_employee_profile_saved_matches_menu"><a href="{% url 'matches:job_posting_saved_matches' %}">{% trans 'Saved Matches' %}</a></li>
<li id="id_employee_profile_automatches_menu"><a href="{% url 'matches:job_posting_automatches' %}">{% trans 'Automatches' %}</a></li>
<li id="id_employee_profile_profile_menu"><a href="{% if user.employeequestionnaire %}{% url 'employee:questionnaire_edit' user.employeequestionnaire.pk %}{% else %}{% url 'employee:questionnaire_add' %}{% endif %}">{% trans 'Profile' %}</a></li>
{% endblock %}
{% block user_profile_menu %}
<li id="id_employee_profile_account_menu"><a href="{% url 'membership:employee_current_plan' %}">{% trans 'Account' %}</a></li>
{% endblock %}
{% block content %}
{% block profile_breadcrumbs %}{% endblock %}
{% include 'base/pagination.html' %}
{% block profile_content %}{% endblock %}
{% include 'base/pagination.html' %}
{% endblock %}

dentexchange/apps/employee/templates/employee/dashboard.html
{% extends 'employee/base.html' %}
{% load static %}
{% load i18n %}
{% block profile_extrahead %}
<link href="{% static 'employee/css/dashboard.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'base/js/ajax.js' %}"></script>
<script type="text/javascript" src="{% static 'employee/js/dashboard.js' %}"></script>
{% endblock %}
{% block profile_content %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="title">{% trans 'Dashboard' %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <h1>{% trans 'Saved Matches' %} (<span id="id_total_saved_matches">{{ matches|length }}</span>)</h1>
        <table id="id_dashboard_matches_table" class="table table-striped table-hover table-responsive">
            <tbody>
                {% for match in matches|slice:':4' %}
                {% with posting=match.match %}
                <tr>
                    <td>
                        <div class="row">
                            <div class="col-sm-12"><big>{{ posting.posting_title }}</big></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <br />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-7">
                                <dl class="match-summary dl-horizontal">
                                    <dt>{% trans 'Profession:' %}</dt>
                                    <dd>{{ posting.get_job_position_display }}</dd>
                                    <dt>{% trans 'Experience:' %}</dt>
                                    <dd>{{ posting.get_experience_years_display }}</dd>
                                    <dt>{% trans 'Salary:' %}</dt>
                                    <dd>{% if posting.hourly_wage %}{{ posting.get_hourly_wage_display }}{% else %}{{ posting.get_annualy_wage_display }}{% endif %}</dd>
                                    <dt>{% trans 'Location:' %}<dt>
                                    <dd>{{ posting.praxis.address }}, {{ posting.praxis.city }}</dd>
                                </dl>
                            </div>
                            <div class="col-sm-4 text-center">
                                <p><big class="matchscore">100%</big><br />Matchscore</p>
                                <p>{% if posting.is_posted and posting.is_active %}<a href="{% url 'employer:view_public_posting_from_list' %}?pk={{ posting.pk }}" class="btn btn-default btn-lg btn-block">View Details</a>{% else %}<span class="label label-danger">Unavailable</span>{% endif %}</p>
                            </div>
                            <div class="col-sm-1">
                                <a class="remove" href="{% url 'matches:delete_job_posting_match' %}?pk={{ posting.pk }}"><span class="glyphicon glyphicon-remove-circle"></span></a>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr>
                    <td>
                        <a href="{% url 'matches:job_posting_saved_matches' %}" class="btn btn-default btn-lg btn-block">{% trans 'See all Saved Matches' %} ></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

dentexchange/apps/employee/templates/employee/public_questionnaire_detail_from_list.html
{% extends 'employee/base.html' %}
{% load static %}
{% load i18n %}
{% load contact %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'matches/js/employer_saved_matches.js' %}"></script>
{% endblock %}
{% block profile_breadcrumbs %}
<ol class="breadcrumb">
    <li><a href="{% url 'matches:questionnaire_saved_matches' %}">&lt; Back to saved matches</a></li>
</ol>
{% endblock %}
{% block profile_content %}
{% if user.userregistration.is_employer %}
<div class="row">
    <div class="col-sm-12 pull-right">
        <div class="pull-right">
            {% contact_button user object %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <br />
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Job Position the employee is looking for' %}</div>
            <div class="panel-body">{{ object.get_job_position_display }}</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Type of Practice' %}</div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Solo Practitioner' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.solo_practitioner %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Multi-Practitioner' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.multi_practitioner %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Corporate' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.corporate %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans "Patient's Method of Payment" %}</div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Fee for Service' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.fee_for_service %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Insurance' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.insurance %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Capitation/Medicaid' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.capitation_medicaid %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Location' %}</div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Zip Code' %}</dt>
                            <dd>{{ object.zip_code }}</dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'City' %}</dt>
                            <dd>{{ object.city }}</dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Sate' %}</dt>
                            <dd>{{ object.get_state_display }}</dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Distance' %}</dt>
                            <dd>{{ object.get_distance_display }}</dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Type of schedule required' %} ({{ object.get_schedule_type_display }})</div>
            <div class="panel-body">
                <ul class="list-group">
                    {% if not object.schedule_type %}
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Monday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.monday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Monday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.monday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Tuesday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.tuesday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Tuesday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.tuesday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Wednesday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.wednesday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Wednesday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.wednesday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Thursday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.thursday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Thursday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.thursday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Friday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.friday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Friday Evening ' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.friday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Saturday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.saturday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Saturday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.saturday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Sunday Daytime' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.sunday_daytime %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Sunday Evening' %}</dt>
                            <dd><span class="glyphicon glyphicon-{% if object.sunday_evening %}ok{% else %}minus{% endif %}-sign"></span></dd>
                        </dl>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Compensation' %} ({{ object.get_compensation_type_display }})</div>
            <div class="panel-body">
                {% if object.compensation_type %}
                <dl class="dl-horizontal">
                    <dt>{% trans 'Annualy Wage' %}</dt>
                    <dd>{{ object.get_annualy_wage_display }}</dd>
                </dl>
                {% else %}
                <dl class="dl-horizontal">
                    <dt>{% trans 'Hourly Wage' %}</dt>
                    <dd>{{ object.get_hourly_wage_display }}</dd>
                </dl>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Education' %}</div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Dental School' %}</dt>
                            <dd>{{ object.dental_school }}</dd>
                        </dl>
                    </li>
                    <li class="list-group-item">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'Graduation Year' %}</dt>
                            <dd>{{ object.get_graduation_year_display }}</dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Visa' %}</div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>{% trans 'US visa' %}</dt>
                    <dd><span class="glyphicon glyphicon-{% if object.visa %}ok{% else %}minus{% endif %}-sign"></span></dd>
                </dl>
            </div>
        </div>
    </div>
</div>
{% if object.specific_strengths %}
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">{% trans 'Specific strengths' %}</div>
            <div class="panel-body">{{ object.specific_strengths }}</div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}