dentexchange/apps/search/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url

from libs.decorators import login_required_for, EMPLOYEE, EMPLOYER
from membership.decorators import enforce_membership
from . import views

urlpatterns = patterns('',
    url(r'^job_postings/$',
        login_required_for(EMPLOYEE)(
        enforce_membership(views.EmployeeSearchView.as_view())),
        name='employee_search'),
    url(r'^job_postings/results/$',
        login_required_for(EMPLOYEE)(
        enforce_membership(views.EmployeeResultsView.as_view())),
        name='employee_results'),
    url(r'^employees/$',
        login_required_for(EMPLOYER)(
        enforce_membership(views.EmployerSearchView.as_view())),
        name='employer_search'),
    url(r'^employees/results/$',
        login_required_for(EMPLOYER)(
        enforce_membership(views.EmployerResultsView.as_view())),
        name='employer_results'),
    url(r'^refresh/beacon/$',
        login_required_for((EMPLOYER, EMPLOYEE))(
        enforce_membership(views.ResultsBeaconView.as_view())),
        name='results_beacon'),
)

dentexchange/apps/search/forms.py
# -*- coding:utf-8 -*-
from django import forms

from libs.mixins.forms import MeaningfulEmptyValueFormMixin
from employee import constants as employee_constants
from . import strings


class SearchForm(forms.Form):
    keywords = forms.CharField(label=strings.SEARCH_FORM_KEYWORDS,
        required=False)
    location = forms.CharField(label=strings.SEARCH_FORM_LOCATION,
        required=False)


class SearchFiltersForm(MeaningfulEmptyValueFormMixin, forms.Form):
    job_position = forms.ChoiceField(
        label=strings.SEARCH_FILTERS_FORM_JOB_POSITION,
        choices=employee_constants.JOB_POSITION_CHOICES,
        required=False)
    experience_years = forms.ChoiceField(
        label=strings.SEARCH_FILTERS_FORM_EXPERIENCE_YEARS,
        choices=employee_constants.EXPERIENCE_YEARS_CHOICES,
        required=False)
    distance = forms.ChoiceField(
        label=strings.SEARCH_FILTERS_FORM_DISTANCE,
        choices=employee_constants.DISTANCE_CHOICES,
        required=False)
    full_time = forms.BooleanField(
        label=strings.SEARCH_FILTERS_FORM_FULL_TIME,
        required=False)
    part_time = forms.BooleanField(
        label=strings.SEARCH_FILTERS_FORM_PART_TIME,
        required=False)
    visa = forms.BooleanField(
        label=strings.SEARCH_FILTERS_FORM_VISA,
        required=False)

dentexchange/apps/search/views.py
# -*- coding:utf-8 -*-
from django.views.generic.base import TemplateView, View
from django.views.generic.list import MultipleObjectMixin

from braces import views

from .tasks import EmployeeSearchResultsTask, EmployerSearchResultsTask
from .forms import SearchForm, SearchFiltersForm
from . import constants


class SearchViewMixin(object):
    def get_context_data(self, **context):
        context = super(SearchViewMixin, self).get_context_data(**context)
        context['form'] = SearchForm()
        context['filters_form'] = SearchFiltersForm()
        context['base_template'] = self.base_template
        return context


class EmployeeSearchView(SearchViewMixin, TemplateView):
    template_name = 'search/employee_search_view.html'
    base_template = 'employee/base.html'


class EmployerSearchView(SearchViewMixin, TemplateView):
    template_name = 'search/employer_search_view.html'
    base_template = 'employer/base.html'


class BaseResultsView(MultipleObjectMixin, views.JSONResponseMixin,
        views.AjaxResponseMixin, View):
    def get_paginate_by(self, queryset):
        return libs_constants.PAGINATE_BY

    def get_ajax(self, request, *args, **kwargs):
        self.task().delay(
            request.GET, request.user, request.session.session_key)
        return self.render_json_response(dict(status='ok'))


class EmployeeResultsView(BaseResultsView):
    task = EmployeeSearchResultsTask


class EmployerResultsView(BaseResultsView):
    task = EmployerSearchResultsTask


class ResultsBeaconView(views.JSONResponseMixin, views.AjaxResponseMixin,
        View):
    def get_ajax(self, request, *args, **kwargs):
        if request.session.has_key(
                constants.RESULTS_BEACON_TASK_DONE_SESSION_KEY):
            results = request.session.pop(
                constants.RESULTS_BEACON_TASK_DONE_SESSION_KEY)
            results.update(dict(done=True))
            return self.render_json_response(results)
        return self.render_json_response(dict(done=False))

dentexchange/apps/search/templates/search/employee_search_view.html
{% extends 'search/search_view.html' %}
{% load i18n %}
{% block search_scripts %}
<script type="text/javascript">
    var save_match_url = "{% url 'matches:add_job_posting_match' %}";
    var view_details_url = "{% url 'employer:view_public_posting_from_list' %}";
    var delete_url = "{% url 'matches:delete_job_posting_match' %}";
</script>
{% endblock %}
{% block search_template %}
{% verbatim %}
<td>
    <p><strong>{{:posting_title}}</strong></p>
    <p>{{:schedule_type}}&nbsp;{{:wage}}</p>
</td>
<td>
    <p>{{:address}}, {{:state}}</p>
    <p>{{:job_position}}</p>
</td>
{% endverbatim %}
{% endblock %}
{% block search_title %}{% trans 'SEARCH FOR JOB POSTINGS' %}{% endblock %}
{% block search_form_action %}{% url 'search:employee_results' %}{% endblock %}

dentexchange/apps/search/templates/search/employer_search_view.html
{% extends 'search/search_view.html' %}
{% load i18n %}
{% block search_scripts %}
<script type="text/javascript">
    var save_match_url = "{% url 'matches:add_questionnaire_match' %}";
    var view_details_url = "{% url 'employee:view_public_questionnaire_from_list' %}";
    var delete_url = "{% url 'matches:delete_questionnaire_match' %}";
</script>
{% endblock %}
{% block search_template %}
{% verbatim %}
<td>{{:schedule_type}}&nbsp;{{:wage}}</td>
<td>
    <p>{{:city}}, {{:state}}&nbsp;({{:distance}})</p>
    <p>{{:job_position}}</p>
</td>
{% endverbatim %}
{% endblock %}
{% block search_title %}{% trans 'SEARCH FOR JOB EMPLOYEES' %}{% endblock %}
{% block search_form_action %}{% url 'search:employer_results' %}{% endblock %}

dentexchange/apps/search/templates/search/search_view.html
{% extends base_template %}
{% load static %}
{% load bootstrap3 %}
{% load i18n %}
{% block profile_extrahead %}
<link href="{% static 'search/css/search.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'base/js/ajax.js' %}"></script>
<script type="text/javascript" src="{% static 'search/js/search.js' %}"></script>
<script type="text/javascript">
    var results_beacon_url = "{% url 'search:results_beacon' %}";
    var save_match_url_caption = "{% trans 'Save' %}";
    var view_details_url_caption = "{% trans 'View Details' %}";
    var empty_results_message = "{% trans 'No results.' %}";
</script>
{% block search_scripts %}
{% endblock %}
<script type="text/x-jsrender" id="search_row_tmpl">
{% verbatim %}
<tr class="vcenter{{if was_saved}} success{{/if}}">
{{:content}}
<td>{{:percentage}}% / {{:score}}</td>
</tr>
{% endverbatim %}
</script>
<script type="text/x-jsrender" id="empty_results_tmpl">
{% verbatim %}
<tr>
    <td class="text-center empty-results-message">{{:empty_results_message}}</td>
</tr>
{% endverbatim %}
</script>
<script type="text/x-jsrender" id="search_content_tmpl">
{% block search_template %}
{% endblock %}
</script>
<script type="text/x-jsrender" id="actions_tmpl">
{% verbatim %}
<td>
    <div class="actions" style="display: none;">
        <div class="row">
            <div class="col-sm-11">
                <a href="{{:view_details_url}}" class="actions-view btn btn-default">{{:view_details_url_caption}}</a>
                <a href="{{:save_match_url}}"{{if was_saved}} style="display: none"{{/if}} class="actions-save btn btn-default">{{:save_match_url_caption}}</a>
                <a href="mailto:{{:contact_email}}?subject={{:contact_email_subject}}&body={{:contact_email_body}}" class="btn btn-default">Contact</a>
            </div>
            <div class="col-sm-1 remove"{{if !was_saved}} style="display: none;"{{/if}}>
                <a class="remove pull-right" href="{{:delete_url}}"><span class="glyphicon glyphicon-remove-circle"></span></a>
            </div>
        </div>
    </div>
</td>
{% endverbatim %}
</script>
{% endblock %}
{% block profile_content %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="title">{% block search_title %}{% endblock %}</h1>
    </div>
</div>
<form class="form-inline" id="id_search_form" action="{% block search_form_action %}{% endblock %}" method="GET" role="form">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            {% bootstrap_field form.keywords layout='inline' %} in {% bootstrap_field form.location layout='inline' %} <button id="id_search_button" type="submit" class="btn btn-primary">{% trans 'Search' %}</button>
            <input type="hidden" id="id_search_hidden" name="_search" value="0" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            <div id="id_show_filters" class="row">
                <div class="col-sm-12">
                    {% trans 'Show Filters' %} <span id="id_filter_button" class="glyphicon glyphicon-chevron-down"></span>
                </div>
            </div>
            <div id="id_filters" class="row" style="display:none;">
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="id_job_position">{{ filters_form.job_position.label }}</label>
                            <br />
                            {% bootstrap_field filters_form.job_position layout='inline' %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <br />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="idfull_time">{% trans 'Type of Schedule' %}</label>
                            <br />
                            {% bootstrap_field filters_form.full_time layout='inline' %}
                            <br />
                            {% bootstrap_field filters_form.part_time layout='inline' %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="id_experience_years">{{ filters_form.experience_years.label }}</label>
                            <br />
                            {% bootstrap_field filters_form.experience_years layout='inline' %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <br />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="id_visa">{% trans 'Visa' %}</label>
                            <br />
                            {% bootstrap_field filters_form.visa layout='inline' %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="id_distance">{{ filters_form.distance.label }}</label>
                            <br />
                            {% bootstrap_field filters_form.distance layout='inline' %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <br />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <button id="id_reset_filters" class="btn btn-default">{% trans 'Reset Filters' %}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-sm-6">
        <h4 id="id_total_items"></h4>
    </div>
    <div class="col-sm-6" style="display: none;">
        <div class="pull-right">
            <span class="glyphicon glyphicon-th-list"></span> <span class="glyphicon glyphicon-th-large"></span>
            {% trans 'Sort by' %}
            <form id="id_sort_by_form" class="form-inline" role="form">
                <div class="form-group">
                    <label class="sr-only" for="id_sort_by">{% trans 'Sort by' %}</label>
                    <select id="id_sort_by" class="form-control">
                        <option>{% trans 'Best Match' %}</option>
                    </select>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-striped table-hover table-responsive" id="id_results_table">
            <tbody>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}