dentexchange/apps/membership/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView

from libs.decorators import login_required_for, EMPLOYEE, EMPLOYER
from . import views

urlpatterns = patterns('',
    url( r'^$',
        login_required_for((EMPLOYEE, EMPLOYER))(
        views.MembershipFormView.as_view()),
        name='home'),
    url(r'^coupon_validation/$',
        login_required_for((EMPLOYEE, EMPLOYER))(
        views.CouponValidationView.as_view()),
        name='coupon_validation'),
    url(r'^employee/current_plan/$',
        login_required_for(EMPLOYEE)(
        TemplateView.as_view(
            template_name='membership/employee_current_plan.html')),
        name='employee_current_plan'),
    url(r'^employer/current_plan/$',
        login_required_for(EMPLOYER)(
        TemplateView.as_view(
            template_name='membership/employer_current_plan.html')),
        name='employer_current_plan'),
)

dentexchange/apps/membership/models.py
# -*- coding:utf-8 -*-
import hashlib
from uuid import uuid4

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.utils.translation import ngettext as _n

from iso3166 import countries

from tinymce.models import HTMLField

from . import strings, constants


class Plan(models.Model):
    title = models.CharField(verbose_name=strings.PLAN_TITLE,
        max_length=50)
    for_employer = models.BooleanField(
        verbose_name=strings.PLAN_FOR_EMPLOYER,
        choices=constants.FOR_EMPLOYER_CHOICES,
        default=constants.FOR_EMPLOYER_CHOICES.EMPLOYER)
    content_description = HTMLField(
        verbose_name=strings.PLAN_CONTENT_DESCRIPTION,
        help_text=strings.PLAN_CONTENT_DESCRIPTION_HELP_TEXT)

    class Meta(object):
        verbose_name = strings.PLAN_VERBOSE_NAME
        verbose_name_plural = strings.PLAN_VERBOSE_NAME_PLURAL
        ordering = ['pk']

    def __unicode__(self):
        return self.title


class PlanPrice(models.Model):
    plan = models.ForeignKey(Plan, verbose_name=strings.PLAN_PRICE_PLAN)
    price = models.DecimalField(verbose_name=strings.PLAN_PRICE_PRICE,
        max_digits=9, decimal_places=2, default=0)
    tag = models.CharField(verbose_name=strings.PLAN_PRICE_TAG,
        max_length=50, blank=True)
    is_free = models.BooleanField(verbose_name=strings.PLAN_PRICE_IS_FREE,
        default=False)
    duration_magnitude = models.PositiveIntegerField(
        verbose_name=strings.PLAN_PRICE_DURATION_MAGNITUDE,
        default=0)
    duration_unit = models.PositiveSmallIntegerField(
        verbose_name=strings.PLAN_PRICE_DURATION_UNIT,
        choices=constants.DURATION_UNIT_CHOICES)
    total_allowed_job_postings = models.PositiveIntegerField(
        verbose_name=strings.PLAN_PRICE_TOTAL_ALLOWED_JOB_POSTINGS,
        default=1)

    class Meta(object):
        verbose_name = strings.PLAN_PRICE_VERBOSE_NAME
        verbose_name_plural = strings.PLAN_PRICE_VERBOSE_NAME_PLURAL

    def __unicode__(self):
        return unicode(self.title)

    @property
    def title(self):
        if self.is_free:
            return strings.PLAN_PRICE_TITLE_FREE
        elif self.duration_unit == constants.DURATION_UNIT_CHOICES.MONTHS:
            singular = strings.PLAN_PRICE_TITLE_MONTH
            plural = strings.PLAN_PRICE_TITLE_MONTH_PLURAL
        else:
            singular = strings.PLAN_PRICE_TITLE_YEAR
            plural = strings.PLAN_PRICE_TITLE_YEAR_PLURAL
        return '%i %s' % (
            self.duration_magnitude,
            _n(singular, plural, self.duration_magnitude))


class Membership(models.Model):
    user = models.OneToOneField(User, verbose_name=strings.MEMBERSHIP_USER)
    # Stripe's customer id
    customer_id = models.CharField(
        verbose_name=strings.MEMBERSHIP_STRIPES_CUSTOMER_ID,
        max_length=100, blank=True, null=True)
    cc_last4 = models.PositiveIntegerField(
        verbose_name=strings.MEMBERSHIP_STRIPES_CC_LAST4,
        null=True)
    # Plan type
    plan_type = models.ForeignKey(PlanPrice,
        verbose_name=strings.MEMBERSHIP_PLAN_TYPE)
    # Purchase Information
    coupon_code = models.ForeignKey('Coupon',
        verbose_name=strings.MEMBERSHIP_COUPON_CODE,
        blank=True, null=True)
    # Contact Information
    first_name = models.CharField(
        verbose_name=strings.MEMBERSHIP_FIRST_NAME,
        max_length=100)
    last_name = models.CharField(
        verbose_name=strings.MEMBERSHIP_LAST_NAME,
        max_length=100)
    email = models.EmailField(
        verbose_name=strings.MEMBERSHIP_EMAIL)
    # Billing Address
    address = models.CharField(
        verbose_name=strings.MEMBERSHIP_ADDRESS,
        max_length=200)
    zip_code = models.DecimalField(
        verbose_name=strings.MEMBERSHIP_ZIP_CODE,
        max_digits=5, decimal_places=0)
    city = models.CharField(
        verbose_name=strings.MEMBERSHIP_CITY,
        max_length=100)
    state = models.CharField(
        verbose_name=strings.MEMBERSHIP_STATE,
        max_length=100)
    country = models.CharField(
        verbose_name=strings.MEMBERSHIP_COUNTRY,
        choices=[(c.alpha2, c.name) for c in countries],
        max_length=2)
    end_date = models.DateTimeField(
        verbose_name=strings.MEMBERSHIP_END_DATE,
        null=True)
    remaining_job_postings = models.PositiveIntegerField(
        verbose_name=strings.MEMBERSHIP_AVAILABLE_JOB_POSTINGS,
        blank=True, default=0)

    class Meta(object):
        verbose_name = strings.MEMBERSHIP_VERBOSE_NAME
        verbose_name_plural = strings.MEMBERSHIP_VERBOSE_NAME_PLURAL

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

    def get_email(self):
        return self.user.email


class CouponManager(models.Manager):
    def is_valid(self, coupon_code):
        if coupon_code is None or coupon_code.strip() == '':
            return False
        return self.get_queryset().filter(
            code=coupon_code, claimed_by__isnull=True).count() > 0

    def get_discount(self, coupon_code):
        return self.get_queryset().get(code=coupon_code).discount


class Coupon(models.Model):
    code = models.CharField(
        verbose_name=strings.COUPON_CODE,
        max_length=10, blank=True, editable=False, unique=True)
    discount = models.DecimalField(
        verbose_name=strings.COUPON_DISCOUNT,
        max_digits=9, decimal_places=2)
    claimed_by = models.OneToOneField(User, verbose_name=strings.COUPON_USER,
        blank=True, null=True, editable=False)
    objects = CouponManager()

    class Meta(object):
        verbose_name = strings.COUPON_VERBOSE_NAME
        verbose_name_plural = strings.COUPON_VERBOSE_NAME_PLURAL

    def __unicode__(self):
        try:
            return strings.COUPON_CLAIMED_UNICODE % (self.code, self.claimed_by)
        except Membership.DoesNotExist:
            return strings.COUPON_UNCLAIMED_UNICODE % self.code

    def get_email(self):
        return self.claimed_by.email

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.code = hashlib.sha512(
                unicode(uuid4())).hexdigest()[:10].upper()
        super(Coupon, self).save(*args, **kwargs)

dentexchange/apps/membership/forms.py
# -*- coding:utf-8 -*-
from django import forms

from form_extensions.fields import CreditCardField

from libs.mixins.forms import (MeaningfulEmptyValueFormMixin,
    UserInitializationFormMixin)
from .models import Membership, Coupon
from . import strings, constants
from .utils import (YearChoices, MembershipStripeAdapter,
    MembershipRestrictionAdapter, MembershipExpirationDateAdapter)


class BillingInfoForm(MeaningfulEmptyValueFormMixin, forms.Form):
    credit_card = CreditCardField(
        label=strings.MEMBERSHIP_CREDIT_CARD)
    cvv = forms.CharField(
        label=strings.MEMBERSHIP_CVV,
        min_length=4)
    expiry_month = forms.ChoiceField(
        label=strings.MEMBERSHIP_EXPIRY_MONTH,
        choices=constants.EXPIRY_MONTH_CHOICES)
    expiry_year = forms.ChoiceField(
        label=strings.MEMBERSHIP_EXPIRY_YEAR,
        choices=YearChoices())

    def __init__(self, *args, **kwargs):
        super(BillingInfoForm, self).__init__(*args, **kwargs)
        self.initialize_data_stripe_attributes()

    def initialize_data_stripe_attributes(self):
        for stripe_field, form_field in \
                constants.STRIPE_TO_FORM_FIELDS_MAPPING.iteritems():
            self.fields[form_field].widget.attrs.update(
                {'data-stripe': stripe_field})


class MembershipForm(MeaningfulEmptyValueFormMixin, UserInitializationFormMixin,
        forms.ModelForm):
    coupon_code = forms.CharField(label=strings.MEMBERSHIP_COUPON_CODE,
        required=False, max_length=10, min_length=10)
    # Billing Address
    zip_code = forms.DecimalField(
        label=strings.MEMBERSHIP_ZIP_CODE,
        max_digits=5, decimal_places=0,
        widget=forms.TextInput)
    non_meaningful_fields = ('plan_type',)
    stripe_token = forms.CharField(widget=forms.HiddenInput)

    class Meta(object):
        model = Membership
        exclude = ('user', 'coupon_code', 'customer_id', 'cc_last4', 'end_date',
            'remaining_job_postings')

    def clean_coupon_code(self):
        data = self.cleaned_data['coupon_code']
        if not (data is None or data.strip() == '' \
                or Coupon.objects.is_valid(data)):
            raise forms.ValidationError(
                strings.MEMBERSHIP_FORM_INVALID_COUPON_ERROR)
        return data

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        instance = super(MembershipForm, self).save(commit=False)
        if cleaned_data['coupon_code'] not in (None, ''):
            coupon = Coupon.objects.get(code=cleaned_data['coupon_code'])
            coupon.claimed_by = instance.user
            coupon.save()
            instance.coupon_code = coupon
        instance.save()
        MembershipExpirationDateAdapter(instance).save_end_date()
        MembershipRestrictionAdapter(instance).reset_restrictions()
        MembershipStripeAdapter(instance).charge_with_token(
            cleaned_data['stripe_token'])
        return instance

dentexchange/apps/membership/templates/membership/current_plan.html
{% load i18n %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="title">{% trans 'Current Membership' %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <p>{% trans 'You are currently enrolled in the:' %}</p>
        <p>${{ user.membership.plan_type.price }} / {{ user.membership.plan_type.title }} membership plan</p>
    </div>
</div>

dentexchange/apps/membership/templates/membership/employee_current_plan.html
{% extends 'employee/base.html' %}
{% load static %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'membership/js/employee_current_plan.js' %}"></script>
{% endblock %}
{% block profile_content %}
{% include 'membership/current_plan.html' %}
{% endblock %}

dentexchange/apps/membership/templates/membership/employer_current_plan.html
{% extends 'employer/base.html' %}
{% load static %}
{% block profile_scripts %}
<script type="text/javascript" src="{% static 'membership/js/employer_current_plan.js' %}"></script>
{% endblock %}
{% block profile_content %}
{% include 'membership/current_plan.html' %}
{% endblock %}

dentexchange/apps/membership/templates/membership/membership_form.html
{% extends 'base/base.html' %}
{% load static %}
{% load url from future %}
{% load bootstrap3 %}
{% load i18n %}
{% block extrahead %}
<link href="{% static 'membership/css/membership.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
    Stripe.setPublishableKey("{{ STRIPE_PUBLISHABLE_KEY }}");
</script>
<script type="text/javascript" src="{% static 'base/js/ajax.js' %}"></script>
<script type="text/javascript" src="{% static 'membership/js/membership.js' %}"></script>
<script type="text/javascript">
    coupon_validation_url = "{% url 'membership:coupon_validation' %}";
</script>
{% endblock %}
{% block content %}
<form method="post" action="{% url 'membership:home' %}" id="id_main_form" role="form">
    {% csrf_token %}
    {{ form.stripe_token }}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <h4>{% trans 'Select your Dentexchange Membership' %}</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <br />
        </div>
    </div>
    {% if form.non_field_errors %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="alert alert-error bg-danger">
                <button type="button" class="btn btn-danger close" data-dismiss="alert" aria-hidden="true">×</button>
                <ul>
                    {% for error in form.non_field_errors %} 
                    <li>{{ error|striptags }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
    {% for plan in plans %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 vcenter">
            <div class="panel panel-default">
                <div class="panel-body plan-type">
                    <table class="table table-striped table-hover table-responsive">
                        <tbody>
                        <tr>
                            <td class="plan-type-name valign"><h3>{{ plan.title }}</h3></td>
                            <td class="plan-type-description">
                                {{ plan.content_description|safe }}
                            </td>
                            <td>
                            <ul class="price-list">
                            {% for price in plan.planprice_set.all %}
                            <li><input type="radio" class="price_radio" name="{{ form.plan_type.html_name }}" value="{{ price.pk }}" amount="{{ price.price }}" title="{{ price.title }}"{% if price.pk|stringformat:"d" == form.plan_type.value %} checked="checked"{% endif %} />&nbsp;{{ price.title }}{% if price.price %}&nbsp;<span class="price">${{ price.price }}</span>{% endif %}{% if price.tag %}&nbsp;<small>{{ price.tag }}</small>{% endif %}</li>
                            {% endfor %}
                            </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <br />
        </div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-sm-4 col-sm-offset-2">
            <div class="row" id="id_purchase_info">
                <div class="col-sm-12">
                    <div id="id_coupon_code_form_group" class="form-group">
                        <label for="id_coupon_code">{% trans 'Purchase Information' %}</label>
                        <div class="row">
                            <div class="col-sm-6">
                                <div id="id_coupon_code_control">
                                    {% bootstrap_field form.coupon_code layout='inline' %}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div id="id_coupon_code_button">
                                    <button type="button" id="id_coupon_code_button" class="btn btn-success">Apply coupon</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="id_first_name">{% trans 'Contact Info' %}</label>
                        {% bootstrap_field form.first_name layout='inline' %}
                        {% bootstrap_field form.last_name layout='inline' %}
                        {% bootstrap_field form.email layout='inline' %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="id_first_name">{% trans 'Billing Address' %}</label>
                        {% bootstrap_field form.address layout='inline' %}
                        {% bootstrap_field form.zip_code layout='inline' %}
                        {% bootstrap_field form.city layout='inline' %}
                        {% bootstrap_field form.state layout='inline' %}
                        {% bootstrap_field form.country layout='inline' %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <br />
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div id="id_summary" style="display: none;">
                <h4>{% trans 'Order Summary' %}</h4>
                <hr />
                <table class="table-responsive order-summary">
                    <tbody>
                        <tr>
                            <td><span id="id_price_title"></span></td>
                            <td class="text-right total">$<span id="id_price_tag"></span></td>
                        </tr>
                        <tr>
                            <td colspan="2"><br /><br /></td>
                        </tr>
                        <tr class="discount" style="display: none;">
                            <td></td>
                            <td><hr /><hr /></td>
                        </tr>
                        <tr class="discount" style="display: none;">
                            <td>Discount</td>
                            <td class="text-right total">-$<span id="id_coupon_discount"></span></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><hr /><hr /></td>
                        </tr>
                        <tr>
                            <td class="text-right">Total</td>
                            <td class="text-right total">$<span id="id_price_total"></span></td>
                        </tr>
                    </tbody>
                </table>
                <br />
                <p>{% trans 'Subscriptions automatically renew until cancelled by changing your account settings. By submitting this order, you agree you will be charged according to your subscription selection.' %}</p>
            </div>
        </div>
    </div>
</form>
<div class="row" id="id_stripe_error" style="display: none;">
    <div class="col-sm-4 col-sm-offset-2">
        <div class="alert alert-error bg-danger">
            <button type="button" class="btn btn-danger close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li></li>
            </ul>
        </div>
    </div>
</div>
<form action="" method="POST" id="id_stripe_form" role="form">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-2">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="id_first_name">{% trans 'Billing Info' %}</label>
                        {% bootstrap_field billing_info_form.credit_card layout='inline' %}
                        {% bootstrap_field billing_info_form.cvv layout='inline' %}
                        {% bootstrap_field billing_info_form.expiry_month layout='inline' %}
                        {% bootstrap_field billing_info_form.expiry_year layout='inline' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-6">
            {% buttons %}
            <button type="submit" id="id_submit" class="btn btn-primary pull-right">SUBSCRIBE</button>
            {% endbuttons %}
        </div>
    </div>
</div>
{% endblock %}